apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: N8N
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi