apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-webui
  name: chroma-pvc
  namespace: n8n
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi