kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/mmartofel/'
  labels:
    app: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: N8N
    app.openshift.io/runtime: redis
  name: redis
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: container
          image: 'registry.redhat.io/rhel9/redis-7:latest'
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
           requests: { cpu: "200m", memory: "512Mi" }
           limits:   { cpu: "1",    memory: "1Gi" }          
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}