kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: n8n
  labels:
    app: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis
spec:
  ports:
  - name: 6379-tcp
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
  sessionAffinity: None